import type { Metadata } from 'next';
import { Sawarabi_Mincho } from 'next/font/google';
import { Footer } from '@/common/Footer';
import { Header } from '@/common/Header';
import './globals.css';

const sawarabiMincho = Sawarabi_Mincho({
  variable: '--font-sawarabi-mincho',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${sawarabiMincho.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
