import type { Metadata } from 'next';
import { Sawarabi_Mincho } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import myIcon from '@/assets/images/my-icon.png';
import './globals.css';

const sawarabiMincho = Sawarabi_Mincho({
  variable: '--font-sawarabi-mincho',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${sawarabiMincho.variable} antialiased`}>
        <header className="sticky top-0 z-10 md:px-14 py-3 px-4 from-brand-start to-brand-end bg-linear-to-b flex justify-between">
          <Link href="/">
            <div className="p-1 rounded-[50%] bg-white w-12 h-12 flex justify-center items-center">
              <Image
                src={myIcon}
                alt="myIcon"
                width={44}
                height={32}
                priority
              />
            </div>
          </Link>
          <nav>
            <ul className="flex gap-x-4 text-white items-center h-full">
              <li>
                <Link href="/skill">Skill</Link>
              </li>
              <li>
                <Link href="/my_products">MyProducts</Link>
              </li>
              <li>
                <a href="https://changeofpace.site">Blog</a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer className="from-brand-start to-brand-end bg-linear-to-b py-3 text-center text-white">
          h-yoshikawa44 Built with Next.js.
        </footer>
      </body>
    </html>
  );
}
